import os

from django.core.management import call_command
from django.core.management.base import BaseCommand

DEFAULT_FIXTURE = os.path.join("boranga", "fixtures", "uat", "uat_fixtures.json")


class Command(BaseCommand):
    """Load the UAT reference-data fixture into the database.

    The fixture is expected to be the single file produced by
    ``scripts/generate_uat_fixtures.sh`` (default: ``boranga/fixtures/uat/uat_fixtures.json``).

    Example usage::

        python manage.py load_uat_fixtures
        python manage.py load_uat_fixtures --fixture-file /path/to/uat_fixtures.json
        python manage.py load_uat_fixtures --dry-run

    """

    help = "Load the UAT reference-data fixture (generated by scripts/generate_uat_fixtures.sh)"

    def add_arguments(self, parser):
        parser.add_argument(
            "--fixture-file",
            default=DEFAULT_FIXTURE,
            help=f"Path to the UAT fixture JSON file (default: {DEFAULT_FIXTURE})",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Show what would be loaded without actually loading it",
        )

    def handle(self, *args, **options):
        fixture_file = options["fixture_file"]
        dry_run = options["dry_run"]

        if not os.path.isfile(fixture_file):
            self.stderr.write(self.style.ERROR(f"Fixture file not found: {fixture_file}"))
            return

        if dry_run:
            self.stdout.write(self.style.WARNING(f"Dry run — would load: {fixture_file}"))
            return

        self.stdout.write(f"Loading {fixture_file} … ", ending="")
        try:
            call_command("loaddata", fixture_file, verbosity=0)
            self.stdout.write(self.style.SUCCESS("OK"))
        except Exception as exc:
            self.stdout.write(self.style.ERROR("FAILED"))
            self.stderr.write(self.style.ERROR(str(exc)))
