import glob
import os

from django.core.management import call_command
from django.core.management.base import BaseCommand


class Command(BaseCommand):
    """Load all UAT reference-data fixtures into the database.

    Fixtures are expected to live in ``boranga/fixtures/uat/`` (the default
    output directory of ``scripts/generate_uat_fixtures.sh``).  Each ``.json``
    file is loaded in the order listed so that models with foreign-key
    dependencies are loaded before the models that reference them.

    Example usage::

        python manage.py load_uat_fixtures
        python manage.py load_uat_fixtures --fixture-dir /path/to/fixtures
        python manage.py load_uat_fixtures --dry-run

    """

    help = "Load UAT reference-data fixtures (generated by scripts/generate_uat_fixtures.sh)"

    # Explicit load order ensures FK dependencies are satisfied.
    # Files present in the directory but NOT listed here are loaded
    # alphabetically after the ordered set.
    ORDERED_FIXTURES = [
        # Geography (Districts depend on Regions)
        "regions",
        "districts",
        # Conservation Status lists before categories (categories have FK to lists)
        "wa_priority_lists",
        "wa_priority_categories",
        "wa_legislative_lists",
        "wa_legislative_categories",
        "iucn_versions",
        "commonwealth_conservation_lists",
        "other_conservation_assessment_lists",
        "conservation_change_codes",
        "proposal_amendment_reasons",
        # Species & Communities
        "group_types",
        "fauna_groups",
        "fauna_sub_groups",  # FK → fauna_groups
        "document_categories",
        "document_sub_categories",  # FK → document_categories
        "threat_categories",
        "threat_agents",
        "current_impacts",
        "potential_impacts",
        "potential_threat_onsets",
        "system_email_groups",
        # Occurrence lookups (no cross-dependencies)
        "observation_times",
        "observer_categories",
        "observer_roles",
        "location_accuracies",
        "coordinate_sources",
        "datums",
        "land_forms",
        "rock_types",
        "soil_types",
        "soil_colours",
        "soil_conditions",
        "drainages",
        "intensities",
        "species_list_relates_to",
        "species_roles",
        "observation_methods",
        "area_assessments",
        "identification_certainties",
        "sample_types",
        "sample_destinations",
        "permit_types",
        "plant_count_methods",
        "plant_count_accuracies",
        "counted_subjects",
        "plant_conditions",
        "animal_behaviours",
        "primary_detection_methods",
        "secondary_signs",
        "reproductive_states",
        "animal_health",
        "death_reasons",
        "wild_statuses",
        "site_types",
        "occurrence_tenure_purposes",
        "occurrence_tenure_vestings",
        # Users / Main / Spatial
        "submitter_categories",
        "file_extension_whitelists",
        "help_text_entries",
        "tile_layers",
        "proxies",
        "geoserver_urls",
        "plausibility_geometries",
        # Ledger
        "system_groups",
    ]

    def add_arguments(self, parser):
        parser.add_argument(
            "--fixture-dir",
            default=os.path.join("boranga", "fixtures", "uat"),
            help="Directory containing the UAT fixture JSON files (default: boranga/fixtures/uat)",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="List the fixtures that would be loaded without loading them",
        )

    def handle(self, *args, **options):
        fixture_dir = options["fixture_dir"]
        dry_run = options["dry_run"]

        if not os.path.isdir(fixture_dir):
            self.stderr.write(self.style.ERROR(f"Fixture directory not found: {fixture_dir}"))
            return

        # Build an ordered list: explicit ordering first, then any extras alpha
        available = {os.path.splitext(os.path.basename(p))[0] for p in glob.glob(os.path.join(fixture_dir, "*.json"))}

        ordered = [s for s in self.ORDERED_FIXTURES if s in available]
        extras = sorted(available - set(ordered))
        to_load = ordered + extras

        if not to_load:
            self.stderr.write(self.style.WARNING("No fixture files found."))
            return

        if dry_run:
            self.stdout.write(self.style.WARNING("Dry run — would load:"))
            for slug in to_load:
                self.stdout.write(f"  {slug}.json")
            return

        self.stdout.write(f"Loading {len(to_load)} fixture(s) from {fixture_dir}/")
        errors = []
        for slug in to_load:
            path = os.path.join(fixture_dir, f"{slug}.json")
            self.stdout.write(f"  {slug}.json … ", ending="")
            try:
                call_command("loaddata", path, verbosity=0)
                self.stdout.write(self.style.SUCCESS("OK"))
            except Exception as exc:
                self.stdout.write(self.style.ERROR("FAILED"))
                errors.append((slug, exc))

        if errors:
            self.stderr.write(self.style.ERROR(f"\n{len(errors)} fixture(s) failed to load:"))
            for slug, exc in errors:
                self.stderr.write(f"  {slug}: {exc}")
        else:
            self.stdout.write(self.style.SUCCESS("\nAll fixtures loaded successfully."))
