# Generated by Django 3.2.20 on 2023-08-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0152_auto_20230728_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floweringperiod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fruitingperiod',
            options={},
        ),
        migrations.AlterField(
            model_name='floweringperiod',
            name='period',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sept', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='fruitingperiod',
            name='period',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sept', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name='speciesconservationattributes',
            name='flowering_period',
        ),
        migrations.AddField(
            model_name='speciesconservationattributes',
            name='flowering_period',
            field=models.ManyToManyField(blank=True, null=True, related_name='curr_flowering_period', to='boranga.FloweringPeriod'),
        ),
        migrations.RemoveField(
            model_name='speciesconservationattributes',
            name='fruiting_period',
        ),
        migrations.AddField(
            model_name='speciesconservationattributes',
            name='fruiting_period',
            field=models.ManyToManyField(blank=True, null=True, related_name='curr_fruiting_period', to='boranga.FruitingPeriod'),
        ),
    ]
