# Generated by Django 3.2.20 on 2023-08-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0155_auto_20230803_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesconservationattributes',
            old_name='flowering_period_id',
            new_name='flowering_period',
        ),
        migrations.RenameField(
            model_name='speciesconservationattributes',
            old_name='fruiting_period_id',
            new_name='fruiting_period',
        ),
    ]
