# Generated by Django 3.2.20 on 2023-08-08 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0154_speciesconservationattributes_flowering_prd'),
        ('boranga', '0156_auto_20230803_1408'),
    ]

    operations = [
    ]
