# Generated by Django 3.2.20 on 2023-08-08 02:29

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0157_merge_20230808_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalamendmentreason',
            options={'verbose_name': 'Proposal Amendment Reason', 'verbose_name_plural': 'Proposal Amendment Reasons'},
        ),
        migrations.RemoveField(
            model_name='speciesconservationattributes',
            name='flowering_period',
        ),
        migrations.AddField(
            model_name='speciesconservationattributes',
            name='flowering_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.floweringperiod'),
        ),
        migrations.AlterField(
            model_name='speciesconservationattributes',
            name='flowering_prd',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=250, null=True),
        ),
        migrations.RemoveField(
            model_name='speciesconservationattributes',
            name='fruiting_period',
        ),
        migrations.AddField(
            model_name='speciesconservationattributes',
            name='fruiting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.fruitingperiod'),
        ),
    ]
