# Generated by Django 3.2.20 on 2023-08-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0160_alter_speciesconservationattributes_breeding_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breedingperiod',
            options={},
        ),
        migrations.AlterField(
            model_name='breedingperiod',
            name='period',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=200, unique=True),
        ),
    ]
