# Generated by Django 5.2.5 on 2025-08-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0589_add_legacyvaluemap_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccToOcrSectionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_system', models.CharField(db_index=True, max_length=50)),
                ('occ_migrated_from_id', models.CharField(db_index=True, max_length=255)),
                ('ocr_migrated_from_id', models.CharField(db_index=True, max_length=255)),
                ('section', models.CharField(choices=[('location', 'Location'), ('habitat_composition', 'Habitat Composition'), ('habitat_condition', 'Habitat Condition'), ('vegetation_structure', 'Vegetation Structure'), ('fire_history', 'Fire History'), ('associated_species', 'Associated Species'), ('observation_detail', 'Observation Detail'), ('plant_count', 'Plant Count'), ('animal_observation', 'Animal Observation'), ('identification', 'Identification')], max_length=64)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('resolved_occ_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('resolved_ocr_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['legacy_system', 'occ_migrated_from_id'], name='boranga_occ_legacy__77e2d5_idx'), models.Index(fields=['legacy_system', 'ocr_migrated_from_id', 'processed'], name='boranga_occ_legacy__32c770_idx'), models.Index(fields=['resolved_occ_id'], name='boranga_occ_resolve_b9467b_idx'), models.Index(fields=['resolved_ocr_id'], name='boranga_occ_resolve_28f56e_idx')],
                'unique_together': {('legacy_system', 'occ_migrated_from_id', 'ocr_migrated_from_id', 'section')},
            },
        ),
    ]
