# Generated by Django 5.2.5 on 2025-09-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0590_alter_communitydocument__file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyUsernameEmailuserMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_system', models.CharField(db_index=True, max_length=50)),
                ('legacy_username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('emailuser_id', models.PositiveIntegerField()),
            ],
        ),
    ]
