# Generated by Django 5.2.5 on 2025-09-01 08:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0591_legacyusernameemailusermapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyusernameemailusermapping',
            name='email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
