# Generated by Django 5.2.5 on 2025-09-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0592_legacyusernameemailusermapping_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
