# Generated by Django 5.2.5 on 2025-09-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0593_alter_communitydocument__file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='taxon_name_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
