# Generated by Django 5.2.5 on 2025-09-17 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0594_alter_communitydocument__file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonpreviousname',
            name='previous_taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_name_from', to='boranga.taxonomy'),
        ),
    ]
