# Generated by Django 5.2.5 on 2025-09-17 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0596_add_previous_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
