# Generated by Django 5.2.5 on 2025-09-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0597_taxonomy_datetime_created_taxonomy_datetime_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxonomy',
            old_name='datetime_modified',
            new_name='datetime_updated',
        ),
    ]
