# Generated by Django 5.2.5 on 2025-09-19 02:15

import boranga.components.occurrence.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0598_rename_datetime_modified_taxonomy_datetime_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationsystem',
            name='classification_system_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='kingdom',
            name='kingdom_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='occurrencereportbulkimporttask',
            name='_associated_files_zip',
            field=models.FileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.occurrence.models.get_occurrence_report_bulk_import_associated_files_path, validators=[boranga.components.occurrence.models.validate_bulk_import_associated_files_extension]),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='kingdom_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomyrank',
            name='taxon_rank_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taxonpreviousname',
            name='previous_name_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taxonvernacular',
            name='vernacular_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='informalgroup',
            index=models.Index(fields=['taxonomy_id', 'classification_system_fk_id'], name='idx_ig_taxonomy_classsys'),
        ),
        migrations.AddIndex(
            model_name='taxonomy',
            index=models.Index(fields=['kingdom_id'], name='idx_taxonomy_kingdom_id'),
        ),
    ]
