# Generated by Django 5.2.7 on 2025-10-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0592_set_xlsx_allow_blank_for_default_fields'),
        ('boranga', '0599_alter_classificationsystem_classification_system_id_and_more'),
    ]

    operations = [
    ]
