# Generated by Django 5.2.7 on 2025-10-30 06:07

import boranga.components.occurrence.models
import django.contrib.gis.db.models.fields
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0601_set_aoo_actual_auto_for_fauna'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastreLayer',
            fields=[
                ('gid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Cadastre layer',
                'verbose_name_plural': 'Cadastre layer',
                'db_table': '"public"."kb_cadastre"',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='occurrencereportbulkimporttask',
            name='_associated_files_zip',
            field=models.FileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.occurrence.models.get_occurrence_report_bulk_import_associated_files_path, validators=[boranga.components.occurrence.models.validate_bulk_import_associated_files_extension]),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='name_currency',
            field=models.BooleanField(default=True),
        ),
    ]
