# Generated by Django 5.2.7 on 2025-10-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0602_cadastrelayer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxonomy',
            old_name='name_currency',
            new_name='is_current',
        ),
    ]
