# Generated by Django 5.2.7 on 2025-11-05 08:58

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0603_rename_name_currency_taxonomy_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occanimalobservation',
            name='secondary_sign',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ocranimalobservation',
            name='secondary_sign',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=250, null=True),
        ),
    ]
