# Generated by Django 5.2.7 on 2025-11-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0604_alter_occanimalobservation_secondary_sign_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occanimalobservation',
            old_name='death_reason',
            new_name='death_injury_reason',
        ),
        migrations.RenameField(
            model_name='ocranimalobservation',
            old_name='death_reason',
            new_name='death_injury_reason',
        ),
    ]
