# Generated by Django 5.2.7 on 2025-11-10 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0605_rename_death_reason_occanimalobservation_death_injury_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitytaxonomy',
            old_name='community_migrated_id',
            new_name='community_common_id',
        ),
    ]
