# Generated by Django 5.2.7 on 2025-11-13 01:42

import boranga.components.occurrence.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0606_rename_community_migrated_id_communitytaxonomy_community_common_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencereportshapefiledocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_report_shapefile_doc_filename),
        ),
        migrations.AlterField(
            model_name='occurrenceshapefiledocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_shapefile_doc_filename),
        ),
    ]
