# Generated by Django 5.2.7 on 2025-11-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0607_update_shapefile_upload_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
