# Generated by Django 5.2.7 on 2025-11-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0608_taxonomy_archived'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taxonomy',
            index=models.Index(fields=['is_current'], name='idx_taxonomy_is_current'),
        ),
        migrations.AddIndex(
            model_name='taxonomy',
            index=models.Index(fields=['archived'], name='idx_taxonomy_archived'),
        ),
    ]
