# Generated by Django 5.2.7 on 2025-11-20 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0609_taxonomy_idx_taxonomy_is_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyTaxonomyMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
                ('legacy_canonical_name', models.CharField(max_length=255)),
                ('taxon_name_id', models.PositiveIntegerField()),
                ('taxonomy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_mappings', to='boranga.taxonomy')),
            ],
            options={
                'indexes': [models.Index(fields=['list_name'], name='idx_legacytax_listname'), models.Index(fields=['taxon_name_id'], name='idx_legacytax_taxonid')],
                'unique_together': {('list_name', 'legacy_canonical_name')},
            },
        ),
    ]
