# Generated by Django 5.2.7 on 2025-11-21 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0610_legacytaxonomymapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('started_by', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('options', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='migration_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_run_communities', to='boranga.migrationrun'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='migration_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='boranga.migrationrun'),
        ),
        migrations.AddField(
            model_name='occurrencereport',
            name='migration_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrence_reports', to='boranga.migrationrun'),
        ),
        migrations.AddField(
            model_name='species',
            name='migration_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_run_species', to='boranga.migrationrun'),
        ),
    ]
