# Generated by Django 5.2.7 on 2025-11-21 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0611_migrationrun_community_migration_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationstatus',
            name='migration_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conservation_statuses', to='boranga.migrationrun'),
        ),
    ]
