# Generated by Django 5.2.7 on 2025-11-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0612_conservationstatus_migration_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrencereport',
            name='approver_comment',
        ),
    ]
