# Generated by Django 5.2.7 on 2025-12-12 03:17

from django.db import migrations

def update_impact_order(apps, schema_editor):
    CurrentImpact = apps.get_model('boranga', 'CurrentImpact')
    PotentialImpact = apps.get_model('boranga', 'PotentialImpact')
    
    # Desired order: Nil, Low, Medium, High, Extreme, Unknown
    order_map = {
        'Nil': 0,
        'Low': 1,
        'Medium': 2,
        'High': 3,
        'Extreme': 4,
        'Unknown': 5
    }
    
    for name, order in order_map.items():
        # Update CurrentImpact
        try:
            obj = CurrentImpact.objects.get(name__iexact=name)
            obj.order = order
            obj.save()
        except CurrentImpact.DoesNotExist:
            pass
            
        # Update PotentialImpact
        try:
            obj = PotentialImpact.objects.get(name__iexact=name)
            obj.order = order
            obj.save()
        except PotentialImpact.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0613_remove_occurrencereport_approver_comment'),
    ]

    operations = [
        migrations.RunPython(update_impact_order),
    ]
