# Generated by Django 5.2.7 on 2025-12-16 06:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0614_auto_20251212_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occobservationdetail',
            name='area_surveyed',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AlterField(
            model_name='occplantcount',
            name='flowering_plants_per',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='ocrobservationdetail',
            name='area_surveyed',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AlterField(
            model_name='ocrplantcount',
            name='flowering_plants_per',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
