# Generated by Django 5.2.9 on 2025-12-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0615_alter_occobservationdetail_area_surveyed_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legacytaxonomymapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='legacytaxonomymapping',
            name='legacy_taxon_name_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
