# Generated by Django 5.2.7 on 2026-01-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0616_alter_legacytaxonomymapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, upload_to='boranga.components.species_and_communities.models.update_community_doc_filename'),
        ),
        migrations.AlterField(
            model_name='speciesdocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, upload_to='boranga.components.species_and_communities.models.update_species_doc_filename'),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='_file',
            field=models.FileField(default=None, max_length=512, upload_to='boranga.components.meetings.models.update_minutes_filename'),
        ),
    ]
