# Generated by Django 5.2.7 on 2026-01-19 08:37

import boranga.components.meetings.models
import boranga.components.species_and_communities.models
import boranga.utils.uploads
import django.contrib.gis.db.models.fields
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0618_alter_occcontactdetail_notes_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffergeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(112.0, -38.5, 129.1, -13.0), null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='communitydocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_community_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.meetings.models.update_meeting_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='occconservationthreat',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='occurrencegeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(112.0, -38.5, 129.1, -13.0), null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='occurrencereportgeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(112.0, -38.5, 129.1, -13.0), null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='occurrencesite',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(112.0, -38.5, 129.1, -13.0), null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='ocrconservationthreat',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='speciesdocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_species_doc_filename, None, True)),
        ),
    ]
