# Generated by Django 5.2.7 on 2026-01-19 08:37

import boranga.components.meetings.models
import boranga.components.species_and_communities.models
import boranga.utils.uploads
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0619_alter_buffergeometry_geometry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_community_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.meetings.models.update_meeting_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='speciesdocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_species_doc_filename, None, True)),
        ),
    ]
