# Generated by Django 5.2.10 on 2026-01-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0620_alter_communitydocument__file_alter_minutes__file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacytaxonomymapping',
            name='legacy_taxon_name_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
