# Generated by Django 5.2.10 on 2026-02-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boranga", "0621_alter_legacytaxonomymapping__legacy_taxon_name_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legacyusernameemailusermapping",
            name="legacy_username",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="legacyusernameemailusermapping",
            unique_together={("legacy_system", "legacy_username")},
        ),
    ]
