# Generated by Django 5.2.10 on 2026-02-05 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0622_alter_legacyusernameemailusermapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityuseraction',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='conservationstatususeraction',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emailuseraction',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meetinguseraction',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='occurrencereportuseraction',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='occurrenceuseraction',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='speciesuseraction',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
