# Generated by Django 5.2.10 on 2026-02-13 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0623_alter_useraction_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsubcategory',
            name='document_sub_category_name',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('[,]', code='comma_not_allowed', inverse_match=True, message='Commas not allowed in the display field for a django lookup.')]),
        ),
        migrations.AlterUniqueTogether(
            name='documentsubcategory',
            unique_together={('document_category', 'document_sub_category_name')},
        ),
    ]
