# Generated by Django 5.2.12 on 2026-03-17 02:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0637_transform_geometries_to_default_srid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffergeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.1, -9.0), null=True, srid=4283),
        ),
        migrations.AlterField(
            model_name='occurrencegeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.1, -9.0), null=True, srid=4283),
        ),
        migrations.AlterField(
            model_name='occurrencereportgeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.1, -9.0), null=True, srid=4283),
        ),
        migrations.AlterField(
            model_name='occurrencesite',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.1, -9.0), null=True, srid=4283),
        ),
        migrations.AlterField(
            model_name='plausibilitygeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4283),
        ),
    ]
