# Generated by Django 5.2.12 on 2026-03-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0638_alter_buffergeometry_geometry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occlocation',
            name='epsg_code',
            field=models.IntegerField(default=4283),
        ),
        migrations.AlterField(
            model_name='ocrlocation',
            name='epsg_code',
            field=models.IntegerField(default=4283),
        ),
    ]
