"""
Migration 0640 — Transform all geometry data from GDA94 (EPSG:4283) to
GDA2020 (EPSG:7844) and update the PostGIS SRID constraint on each column.

This follows the same pattern as migration 0637 (WGS84 → GDA94).
The subsequent AlterField migration is auto-generated by makemigrations and
MUST depend on this migration so that data is transformed before column
metadata is updated.
"""

from django.db import migrations

# ----- Edit these two values when performing a future CRS change -----
OLD_SRID = 4283
NEW_SRID = 7844
# ---------------------------------------------------------------------

# All (table_name, geometry_column) pairs that need transforming.
# Add new geometry tables here if they are created after this migration.
GEOMETRY_COLUMNS = [
    ("boranga_occurrencereportgeometry", "geometry"),
    ("boranga_occurrencegeometry", "geometry"),
    ("boranga_buffergeometry", "geometry"),
    ("boranga_occurrencesite", "geometry"),
    ("boranga_plausibilitygeometry", "geometry"),
    # CadastreLayer is unmanaged (managed=False), so we handle it separately
    # only if it exists.  Uncomment if you want to include it:
    # ('"public"."kb_cadastre"', "geom"),
]


def transform_forward(apps, schema_editor):
    """Transform geometry data from OLD_SRID to NEW_SRID."""
    if OLD_SRID == NEW_SRID:
        return  # Nothing to do

    with schema_editor.connection.cursor() as cursor:
        for table, column in GEOMETRY_COLUMNS:
            # Check if table exists (safety for optional/unmanaged tables)
            cursor.execute(
                "SELECT EXISTS ("
                "  SELECT FROM information_schema.tables "
                "  WHERE table_name = %s"
                ")",
                [table.strip('"').split(".")[-1].strip('"')],
            )
            if not cursor.fetchone()[0]:
                continue

            # Update the SRID constraint on the column FIRST so PostGIS
            # allows writing transformed (NEW_SRID) data into the column.
            cursor.execute(
                "SELECT UpdateGeometrySRID(%s, %s, %s)",
                [table, column, NEW_SRID],
            )

            # Transform all non-NULL geometries
            cursor.execute(
                f"UPDATE {table} SET {column} = ST_Transform({column}, %s) "
                f"WHERE {column} IS NOT NULL AND ST_SRID({column}) = %s",
                [NEW_SRID, OLD_SRID],
            )


def transform_reverse(apps, schema_editor):
    """Reverse: transform geometry data from NEW_SRID back to OLD_SRID."""
    if OLD_SRID == NEW_SRID:
        return

    with schema_editor.connection.cursor() as cursor:
        for table, column in GEOMETRY_COLUMNS:
            cursor.execute(
                "SELECT EXISTS ("
                "  SELECT FROM information_schema.tables "
                "  WHERE table_name = %s"
                ")",
                [table.strip('"').split(".")[-1].strip('"')],
            )
            if not cursor.fetchone()[0]:
                continue

            cursor.execute(
                "SELECT UpdateGeometrySRID(%s, %s, %s)",
                [table, column, OLD_SRID],
            )

            cursor.execute(
                f"UPDATE {table} SET {column} = ST_Transform({column}, %s) "
                f"WHERE {column} IS NOT NULL AND ST_SRID({column}) = %s",
                [OLD_SRID, NEW_SRID],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0639_alter_communitydocument__file_alter_minutes__file_and_more"),
    ]

    operations = [
        migrations.RunPython(
            transform_forward,
            transform_reverse,
            elidable=False,
        ),
    ]
