# Generated by Django 5.2.12 on 2026-03-26 02:49

import boranga.components.meetings.models
import boranga.components.species_and_communities.models
import boranga.utils.uploads
import django.contrib.gis.db.models.fields
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0640_transform_geometries_4283_to_7844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffergeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.1, -9.0), null=True, srid=7844),
        ),
        migrations.AlterField(
            model_name='communitydocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_community_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.meetings.models.update_meeting_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='occlocation',
            name='epsg_code',
            field=models.IntegerField(default=7844),
        ),
        migrations.AlterField(
            model_name='occurrencegeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.1, -9.0), null=True, srid=7844),
        ),
        migrations.AlterField(
            model_name='occurrencereportgeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.1, -9.0), null=True, srid=7844),
        ),
        migrations.AlterField(
            model_name='occurrencesite',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.1, -9.0), null=True, srid=7844),
        ),
        migrations.AlterField(
            model_name='ocrlocation',
            name='epsg_code',
            field=models.IntegerField(default=7844),
        ),
        migrations.AlterField(
            model_name='plausibilitygeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=7844),
        ),
        migrations.AlterField(
            model_name='speciesdocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_species_doc_filename, None, True)),
        ),
    ]
