# Generated by Django 5.2.12 on 2026-03-31 11:47

import boranga.components.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0641_alter_buffergeometry_geometry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_cmd', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Running'), (2, 'Completed'), (3, 'Failed')], default=0)),
                ('parameters_json', models.JSONField(blank=True, null=True)),
                ('processed_dt', models.DateTimeField(blank=True, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Job Queue',
            },
            bases=(boranga.components.main.models.SanitisationModelMixin, models.Model),
        ),
    ]
