# Generated by Django 5.2.12 on 2026-03-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0642_add_job_queue_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobqueue',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),

    ]
