# Generated by Django 5.2.12 on 2026-04-07 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0643_add_job_queue_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationSourceChecksum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler_slug', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('target_table', models.CharField(max_length=150)),
                ('checksum', models.CharField(max_length=32)),
                ('row_count', models.PositiveIntegerField()),
                ('phase', models.CharField(choices=[('pre', 'Pre-run'), ('post', 'Post-run')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('migration_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_checksums', to='boranga.migrationrun')),
            ],
            options={
                'unique_together': {('migration_run', 'handler_slug', 'source', 'target_table', 'phase')},
            },
        ),
    ]
