# Generated by Django 5.2.12 on 2026-04-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0644_migration_source_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencereport',
            name='locked',
            field=models.BooleanField(default=False, help_text='Whether the record is locked'),
        ),
        migrations.AlterField(
            model_name='occurrencereport',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='occurrencereport',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('with_approver', 'With Approver'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('closed', 'Delisted')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
    ]
