# Generated by Django 5.2.13 on 2026-04-22 06:33

import boranga.components.meetings.models
import boranga.components.species_and_communities.models
import boranga.utils.uploads
import django.core.files.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0648_rename_reported_date_to_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_community_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.meetings.models.update_meeting_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='datetime_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='speciesdocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_species_doc_filename, None, True)),
        ),
    ]
