# Generated by Django 5.2.13 on 2026-04-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0650_occurrence_report_datetime_updated_no_autonow'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencetenure',
            name='cad_pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
