# Generated by Django 5.2.13 on 2026-05-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0651_occurrence_tenure_cad_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencereportapprovaldetails',
            name='officer',
            field=models.IntegerField(null=True),
        ),
    ]
