# Generated by Django 5.2.13 on 2026-05-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0652_alter_communitydocument__file_alter_minutes__file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='review_status',
        ),
    ]
