# Generated by Django 5.2.13 on 2026-05-04 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0653_remove_occurrence_review_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occlocation',
            name='buffer_radius',
        ),
        migrations.RemoveField(
            model_name='occlocation',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='occlocation',
            name='epsg_code',
        ),
        migrations.RemoveField(
            model_name='ocrlocation',
            name='buffer_radius',
        ),
        migrations.RemoveField(
            model_name='ocrlocation',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='ocrlocation',
            name='epsg_code',
        ),
    ]
