# Generated by Django 5.2.13 on 2026-05-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0654_remove_datum_buffer_radius_epsg_code_from_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitytaxonomy',
            name='community_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
