# Generated by Django 5.2.13 on 2026-05-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0655_community_description_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservationthreat',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
