# Generated by Django 5.2.14 on 2026-05-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0656_alter_conservation_threat_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.UniqueConstraint(condition=models.Q(('community__isnull', True)), fields=('occurrence_name', 'species'), name='unique_occurrence_name_per_species'),
        ),
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.UniqueConstraint(condition=models.Q(('species__isnull', True)), fields=('occurrence_name', 'community'), name='unique_occurrence_name_per_community'),
        ),
    ]
