# Generated by Django 5.2.14 on 2026-05-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0657_fix_occurrence_name_unique_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='occurrence',
            name='unique_occurrence_name_per_species',
        ),
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.UniqueConstraint(condition=models.Q(('community__isnull', True)), fields=('occurrence_name', 'group_type', 'species'), name='unique_occurrence_name_per_species'),
        ),
    ]
