# Generated by Django 5.2.14 on 2026-05-20 08:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0658_remove_occurrence_unique_occurrence_name_per_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffergeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.2, -9.0), null=True, srid=7844),
        ),
        migrations.AlterField(
            model_name='occurrencegeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.2, -9.0), null=True, srid=7844),
        ),
        migrations.AlterField(
            model_name='occurrencereportgeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.2, -9.0), null=True, srid=7844),
        ),
        migrations.AlterField(
            model_name='occurrencesite',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.2, -9.0), null=True, srid=7844),
        ),
    ]
