# Generated by Django 5.2.14 on 2026-05-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0659_alter_geometry_extent_129_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencereportapprovaldetails',
            name='officer',
            field=models.IntegerField(),
        ),
    ]
