# Generated by Django 5.2.14 on 2026-05-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0661_fix_stale_allow_blank_schema_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrencegeometry',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='occurrencereportgeometry',
            name='locked',
        ),
        migrations.AddField(
            model_name='buffergeometry',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='occurrencegeometry',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='occurrencereportgeometry',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
