# Generated by Django 5.2.14 on 2026-06-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0662_geometry_discard'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationstatus',
            name='commonwealth_conservation_categories',
            field=models.ManyToManyField(blank=True, related_name='curr_commonwealth_conservation_categories', to='boranga.commonwealthconservationlist'),
        ),
    ]
