# Generated by Django 5.2.14 on 2026-06-03 02:02

from django.db import migrations

def copy_fk_to_m2m(apps, schema_editor):
    APP_NAME = 'boranga'
    MODEL_NAME = 'ConservationStatus'
    
    ConservationStatus = apps.get_model(APP_NAME, MODEL_NAME)
    
    # Access Django's hidden intermediate join table model dynamically
    ThroughModel = ConservationStatus.commonwealth_conservation_categories.through
    
    # Introspect field names on the through model to avoid naming guessing games
    fields = ThroughModel._meta.fields
    fk_to_source_field = [f.attname for f in fields if f.remote_field and f.remote_field.model == ConservationStatus][0]
    fk_to_target_field = [f.attname for f in fields if f.remote_field and f.remote_field.model != ConservationStatus][0]

    # Query only the necessary IDs from records where the FK is populated
    queryset = ConservationStatus.objects.exclude(
        commonwealth_conservation_category__isnull=True
    ).values_list('id', 'commonwealth_conservation_category_id')
    
    relations_to_create = []
    for source_id, target_id in queryset:
        # Dynamically build kwargs to match exact through-table column names
        kwargs = {
            fk_to_source_field: source_id,
            fk_to_target_field: target_id
        }
        relations_to_create.append(ThroughModel(**kwargs))
    
    # Insert all records in fast, optimized database batches
    if relations_to_create:
        ThroughModel.objects.bulk_create(relations_to_create, batch_size=1000)

def reverse_m2m_to_fk(apps, schema_editor):
    APP_NAME = 'boranga'
    MODEL_NAME = 'ConservationStatus'
    
    ConservationStatus = apps.get_model(APP_NAME, MODEL_NAME)
    ThroughModel = ConservationStatus.commonwealth_conservation_categories.through
    
    fields = ThroughModel._meta.fields
    fk_to_source_field = [f.name for f in fields if f.remote_field and f.remote_field.model == ConservationStatus][0]
    fk_to_target_field = [f.name for f in fields if f.remote_field and f.remote_field.model != ConservationStatus][0]

    # Find the first M2M connection for every source record
    m2m_mappings = ThroughModel.objects.order_by('id').values_list(fk_to_source_field, fk_to_target_field)
    
    # Map the first encountered target ID to each source ID
    first_match_map = {}
    for source_id, target_id in m2m_mappings:
        if source_id not in first_match_map:
            first_match_map[source_id] = target_id
            
    # Bulk update the source rows back to their original FK values
    updated_records = []
    for source_id, target_id in first_match_map.items():
        record = ConservationStatus(id=source_id, commonwealth_conservation_category_id=target_id)
        updated_records.append(record)
        
    if updated_records:
        ConservationStatus.objects.bulk_update(updated_records, ['commonwealth_conservation_category'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        # Ensure this dependency points to the migration that CREATED the M2M field
        ('boranga', '0663_conservationstatus_commonwealth_conservation_categories_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_fk_to_m2m, reverse_code=reverse_m2m_to_fk),
    ]
