# Generated by Django 5.2.14 on 2026-06-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0664_auto_20260603_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conservationstatus',
            name='commonwealth_conservation_category',
        ),
    ]
