# Generated by Django 5.2.15 on 2026-06-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0665_remove_conservationstatus_commonwealth_conservation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobqueue',
            name='started_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
