# Generated by Django 5.2.15 on 2026-06-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0666_jobqueue_started_dt_alter_communitydocument__file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobqueue',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
