# Generated by Django 5.2.14 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0668_occurrencereportbulkimporttask_history_seeded"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationstatus",
            name="other_conservation_assessments",
            field=models.ManyToManyField(
                blank=True,
                related_name="curr_other_conservation_assessments",
                to="boranga.otherconservationassessmentlist",
            ),
        ),
    ]
