# Generated by Django 5.2.14 on 2026-06-24

from django.db import migrations


def copy_other_conservation_assessment_to_m2m(apps, schema_editor):
    ConservationStatus = apps.get_model("boranga", "ConservationStatus")
    for cs in ConservationStatus.objects.filter(
        other_conservation_assessment__isnull=False
    ).iterator():
        cs.other_conservation_assessments.add(cs.other_conservation_assessment)


def reverse_copy(apps, schema_editor):
    # Reverse: set the FK from the first M2M entry (best-effort)
    ConservationStatus = apps.get_model("boranga", "ConservationStatus")
    for cs in ConservationStatus.objects.prefetch_related(
        "other_conservation_assessments"
    ).iterator():
        first = cs.other_conservation_assessments.first()
        if first:
            cs.other_conservation_assessment = first
            cs.save(update_fields=["other_conservation_assessment"])


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0669_conservationstatus_other_conservation_assessments"),
    ]

    operations = [
        migrations.RunPython(
            copy_other_conservation_assessment_to_m2m,
            reverse_code=reverse_copy,
        ),
    ]
