# Generated by Django 5.2.14 on 2026-06-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0670_copy_other_conservation_assessment_to_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatus",
            name="other_conservation_assessment",
        ),
    ]
