# Generated by Django 5.2.15 on 2026-06-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0671_remove_conservationstatus_other_conservation_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
