# Generated by Django 5.2.15 on 2026-06-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0672_alter_communitydocument__file_alter_minutes__file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='conservation_plan_reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
