# Generated by Django 5.2.15 on 2026-07-07 06:24

import boranga.components.meetings.models
import boranga.components.species_and_communities.models
import boranga.utils.uploads
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0673_alter_communitydocument__file_alter_minutes__file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencereportbulkimporttask',
            name='column_count',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='communitydocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_community_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.meetings.models.update_meeting_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='speciesdocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_species_doc_filename, None, True)),
        ),
    ]
