# Generated by Django 5.2.15 on 2026-07-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0673_alter_communitydocument__file_alter_minutes__file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencereportbulkimporttask',
            name='column_count',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
